### ISSUE TITLE
Cant updare old machines due to lack of machine update key

### ISSUE THREAD

**Issue by Kilill** [alexloehner/linuxcounter-update-examples#5]
Older machines does not seem to have an update key, therefore the script is unable to update the existing machines, it only reports on creating a new machine, there should be an option to create a update key if none exists.

**Comment by alexloehner** [comment]
thanks for this. I was not aware of that. I'll add random updatekeys to machines that has none. Thanks.

**Comment by alexloehner** [comment]
I've just created updatekeys for ALL old machines that havn't got one until now.
So please look into your profile to see your updatekeys.
Thanks!
